// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerStats.achievements")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerStats.gameName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerStats.steamID")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerStats.success")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerStatsError.error")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerStatsError.success")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerAchievement.achieved")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerAchievement.apiname")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerAchievement.description")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerAchievement.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerAchievementsForApp.playerstats")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerAchievementsForAppError.playerstats")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.PlayerResponse.players")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.avatar")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.avatarfull")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.avatarmedium")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.commentpermission")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.communityvisibilitystate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.lastlogoff")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.personaname")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.personastate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.personastateflags")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.primaryclanid")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.profilestate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.profileurl")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.steamid")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayer.timecreated")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamPlayerDetail.response")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.AvailableGameStats.achievements")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Friendslist.friends")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.defaultvalue")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.description")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.displayName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.hidden")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.icon")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.icongray")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.GameAchievement.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Message.appid")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Message.has_community_visible_stats")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Message.img_icon_url")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Message.img_logo_url")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Message.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.Message.playtime_forever")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.OwnedGamesResponse.game_count")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.OwnedGamesResponse.games")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamFriend.friend_since")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamFriend.relationship")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamFriend.steamid")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamFriendList.friendslist")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGame.availableGameStats")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGame.gameName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGame.gameVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGameDetail.game")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGlobalAchievement.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGlobalAchievement.percent")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGlobalAchievements.achievements")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamGlobalAchievementsForApp.achievementpercentages")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SamSmithNZ.Service.Models.Steam.SteamOwnedGames.response")]
[assembly: SuppressMessage("Usage", "CA2249:Consider using 'string.Contains' instead of 'string.IndexOf'", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamPlayerAchievementsForAppDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Tuple{SamSmithNZ.Service.Models.Steam.SteamPlayerAchievementsForApp,SamSmithNZ.Service.Models.Steam.SteamPlayerAchievementsForAppError}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamFriendDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.Boolean)~System.Threading.Tasks.Task{SamSmithNZ.Service.Models.Steam.SteamFriendList}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamGameDetailDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.Boolean)~System.Threading.Tasks.Task{SamSmithNZ.Service.Models.Steam.SteamGameDetail}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamGlobalAchievementPercentagesForAppDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.Boolean)~System.Threading.Tasks.Task{SamSmithNZ.Service.Models.Steam.SteamGlobalAchievementsForApp}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamOwnedGamesDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.Boolean)~System.Threading.Tasks.Task{SamSmithNZ.Service.Models.Steam.SteamOwnedGames}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamPlayerAchievementsForAppDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Tuple{SamSmithNZ.Service.Models.Steam.SteamPlayerAchievementsForApp,SamSmithNZ.Service.Models.Steam.SteamPlayerAchievementsForAppError}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.SteamPlayerDetailDA.GetDataAsync(SamSmithNZ.Service.DataAccess.Steam.Interfaces.IRedisService,System.String,System.Boolean)~System.Threading.Tasks.Task{SamSmithNZ.Service.Models.Steam.SteamPlayerDetail}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.TextStats.AddItem(System.String,System.Char)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:SamSmithNZ.Service.DataAccess.Steam.TextStats.SortList(System.Boolean)~System.Collections.Generic.List{System.Collections.Generic.KeyValuePair{System.String,System.Int32}}")]
